### ISSUE TITLE
ld: warning: Could not find auto-linked framework 'FBLPromises'  Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by timxie-88** [nboy1/Admob-for-Flash-ANE-GMA21-GLM-#5]
I am trying to publish to ios in Adobe Animate and get the error, Could not sign the ipa file

**Comment by timxie-88** [comment]
I use AIR 50.2.3.5 the newest one, i dont know how to fixed it

**Comment by timxie-88** [comment]
anyone know?

**Comment by nboy1** [comment]
> anyone know?

hi, can you give a screen shoot of the error and more details about it.

**Comment by timxie-88** [comment]
I used Adobe Animate 2018 to publish ipa files in windows7.
An error occurred while creating the file.

Warning: ipa-app-store build but provisioning profile does not have beta-reports-active entitlement.

ld: warning: Could not find auto-linked framework 'FBLPromises'

Undefined symbols for architecture arm64:

   "_objc_msgSend$loadWithAdUnitID:request:orientation:completionHandler:", referenced from:

       _showAppOpenAd in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

       ___showAppOpenAd_block_invoke_3 in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$statusBarOrientation", referenced from:

       _getInterfaceOrientation in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$type", referenced from:

       ___showRewardedInterstitialAd_block_invoke in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$longValue", referenced from:

       ___showRewardedInterstitialAd_block_invoke in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$presentFromRootViewController:userDidEarnRewardHandler:", referenced from:

       _showRewardedInterstitialAd in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$setContext:", referenced from:

       _loadRewardedInterstitialAd in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$setFullScreenContentDelegate:", referenced from:

       _loadRewardedInterstitialAd in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

       ___loadRewardedInterstitialAd_block_invoke_2 in C:\Users\tim\AppData\Local\Temp\8f7616cf-6b51-4c50-b821-37ebe886da88\libcom.glm.admob.a(admob.o)

   "_objc_msgSend$removeFromSuperview", referenced from:

       _FREhideAdaptiveBanner in C:
